/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hastaneyönetimsistemi;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ardas
 */
public class Yonetim_UI extends javax.swing.JFrame {
    DefaultTableModel model;
    baglanti baglanti = new baglanti();

    public Yonetim_UI() {
        initComponents();
        model = (DefaultTableModel) hasta_tablosu.getModel();
        hastalariGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        hasta_tablosu = new javax.swing.JTable();
        arama_alani = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        hasta_ekle = new javax.swing.JButton();
        hasta_sil = new javax.swing.JButton();
        hasta_guncelle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 500, 500));

        hasta_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ad", "Soyad", "Tc No", "Hastalık", "Derece"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(hasta_tablosu);
        if (hasta_tablosu.getColumnModel().getColumnCount() > 0) {
            hasta_tablosu.getColumnModel().getColumn(0).setResizable(false);
            hasta_tablosu.getColumnModel().getColumn(1).setResizable(false);
            hasta_tablosu.getColumnModel().getColumn(2).setResizable(false);
            hasta_tablosu.getColumnModel().getColumn(3).setResizable(false);
            hasta_tablosu.getColumnModel().getColumn(4).setResizable(false);
        }

        arama_alani.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_alaniKeyReleased(evt);
            }
        });

        hasta_ekle.setText("Hasta Ekle");
        hasta_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasta_ekleActionPerformed(evt);
            }
        });

        hasta_sil.setText("Hasta Sil");
        hasta_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasta_silActionPerformed(evt);
            }
        });

        hasta_guncelle.setText("Hasta Güncelle");
        hasta_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasta_guncelleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arama_alani)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hasta_sil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hasta_guncelle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(hasta_ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(arama_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hasta_ekle)
                        .addGap(18, 18, 18)
                        .addComponent(hasta_sil)
                        .addGap(18, 18, 18)
                        .addComponent(hasta_guncelle)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void dinamikAra(String ara){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(model);
        hasta_tablosu.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    

    public void hastalariGoruntule(){
        model.setRowCount(0);
        ArrayList<hasta> arraylist;
        arraylist = baglanti.hastalariGetir();
        if(arraylist!= null){
            for(hasta hasta : arraylist){
                Object[] eklenecek = {hasta.getAd(),hasta.getSoyad(),hasta.getTc(),hasta.getHastalık(),hasta.getDerece()};
                model.addRow(eklenecek);
            }
        }
    }
    private void hasta_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasta_ekleActionPerformed
        Ekle_UI ekle = new Ekle_UI();
        
        ekle.show();
        setVisible(false);
    }//GEN-LAST:event_hasta_ekleActionPerformed

    private void hasta_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasta_silActionPerformed
        int selected_row = hasta_tablosu.getSelectedRow();
        if(selected_row!=-1){
        String ad = (String) model.getValueAt(selected_row, 0);
        baglanti.hasta_sil(ad);
        model.removeRow(selected_row);
        }
        else{
            if(model.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Tablo boş.");
            }
            else{
                JOptionPane.showMessageDialog(this, "Lütfen silinecek bir hasta seçiniz.");
            }
        }
        
        
    }//GEN-LAST:event_hasta_silActionPerformed

    private void hasta_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasta_guncelleActionPerformed
        int selected_row = hasta_tablosu.getSelectedRow();
        
        if(selected_row==-1){
            if(model.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Tablo boş.");
            }
            else{
                JOptionPane.showMessageDialog(this, "Lütfen güncellenecek bir hasta seçiniz.");
            }
        }
        else{
            String eski_ad = (String)model.getValueAt(selected_row, 0);
            String eski_soyad = (String)model.getValueAt(selected_row, 1);
            String eski_tc = (String)model.getValueAt(selected_row, 2);
            String eski_hastalik = (String)model.getValueAt(selected_row, 3);
            int eski_derece = (int)model.getValueAt(selected_row, 4);
            Ekle_UI ekle = new Ekle_UI(eski_ad, eski_soyad, eski_tc, eski_hastalik, eski_derece);
            ekle.show();
            setVisible(false);
        }
    }//GEN-LAST:event_hasta_guncelleActionPerformed

    private void arama_alaniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_alaniKeyReleased
        String s = arama_alani.getText();
        dinamikAra(s);
    }//GEN-LAST:event_arama_alaniKeyReleased
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Yonetim_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Yonetim_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Yonetim_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Yonetim_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Yonetim_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arama_alani;
    private javax.swing.JButton hasta_ekle;
    private javax.swing.JButton hasta_guncelle;
    private javax.swing.JButton hasta_sil;
    private javax.swing.JTable hasta_tablosu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
